version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Messi1987@
      MYSQL_DATABASE: test
      MYSQL_USER: ayoub
      MYSQL_PASSWORD: Messi1987@
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Messi1987@
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
